name: mkxref-dev
channels:
  - conda-forge

dependencies:
  # runtime
  - python >=3.9,<3.14
  - mkdocstrings-python >=1.14,<2.0
  - griffe >=1.0
  # build
  - python-build >=1.0.0
  - hatchling >=1.21
  # test
  - coverage >=7.4.0
  - pytest >=8.2
  - pytest-cov >=5.0
  - pylint >=3.0.3
  - mypy >=1.10
  - ruff >=0.4.10
  - beautifulsoup4 >=4.12
  # documentation
  - black >=23.12
  - mike >=1.1,<2.0
  - mkdocs >=1.5.3,<2.0
  - mkdocs-material >=9.5.4
  - linkchecker >=10.4
